//
//  RCMediaMessageContent.h
//  RongIMLib
//
//  Created by lichenfeng on 2018/11/22.
//  Copyright © 2018 RongCloud. All rights reserved.
//

#import "RCMessageContent.h"

/**
 *  \~chinese
 媒体类型消息的父类

 @discussion
 SDK 中所有媒体类型消息（图片、文件等）均继承此类。
 开发者如需将自定义的媒体类型消息上传到融云默认的服务器时必须继承此类 ( SDK 负责媒体消息的上传及上传成功后的发送，开发者自行处理消息接收后的展示) 。
 以下属性需要子类在 encode、decode 方法中和扩展的属性一同进行处理
 
 *  \~english
 The parent class of the media type message.

 @ discussion
 All media type messages (images, files, and so on) in SDK inherit this class.
  Developers who shall upload custom media type messages to RongCloud's default server must inherit this class (SDK is responsible for uploading and sending media messages successfully, and developers handle the display after receiving messages).
  The following properties shall be processed by subclasses in the encode and decode methods along with the extended properties.
 */
@interface RCMediaMessageContent : RCMessageContent

/**
 *  \~chinese
 媒体内容的本地路径（此属性必须有值）
 
 *  \~english
 The local path to the media content (this property must have a value).
 */
@property (nonatomic, copy) NSString *localPath;

/**
 *  \~chinese
 媒体内容上传服务器后的网络地址（上传成功后 SDK 会为该属性赋值）
 
 *  \~english
 The network address after the media content is uploaded to the server (SDK will assign a value to this attribute after the upload is successful).
 */
@property (nonatomic, copy) NSString *remoteUrl;

/**
 *  \~chinese
 媒体内容的文件名（如不传使用 SDK 中 downloadMediaMessage 方法下载后会默认生成一个名称）
 
 *  \~english
 The file name of the media content (if not passed, a name will be generated by default after downloading using the downloadMediaMessage method in SDK).
 */
@property (nonatomic, copy) NSString *name;
@end
